/**
 * Auto-generated by scripts/extract-trailer-chunks.mjs
 * Fan/dev media plates — not affiliated with Rockstar.
 */
export type CinemaClip = {
  id: string;
  label: string;
  videoSrc: string;
  posterSrc: string;
  duration: number;
  source: "t1" | "t2";
};

export const cinemaClips = [
  {
    "id": "hero-scrub",
    "label": "Hero scroll scrub",
    "videoSrc": "/videos/cinema/hero-scrub.mp4",
    "posterSrc": "/images/cinema/hero-scrub.jpg",
    "duration": 5.5,
    "source": "t2"
  },
  {
    "id": "coast-loop",
    "label": "Coast full-bleed loop",
    "videoSrc": "/videos/cinema/coast-loop.mp4",
    "posterSrc": "/images/cinema/coast-loop.jpg",
    "duration": 6,
    "source": "t2"
  },
  {
    "id": "neon-loop",
    "label": "Neon night loop",
    "videoSrc": "/videos/cinema/neon-loop.mp4",
    "posterSrc": "/images/cinema/neon-loop.jpg",
    "duration": 6,
    "source": "t2"
  },
  {
    "id": "heat-loop",
    "label": "Heat / motion loop",
    "videoSrc": "/videos/cinema/heat-loop.mp4",
    "posterSrc": "/images/cinema/heat-loop.jpg",
    "duration": 5.5,
    "source": "t2"
  },
  {
    "id": "vice-pulse",
    "label": "Vice pulse",
    "videoSrc": "/videos/cinema/vice-pulse.mp4",
    "posterSrc": "/images/cinema/vice-pulse.jpg",
    "duration": 5,
    "source": "t1"
  },
  {
    "id": "chase-cut",
    "label": "Chase cut",
    "videoSrc": "/videos/cinema/chase-cut.mp4",
    "posterSrc": "/images/cinema/chase-cut.jpg",
    "duration": 5,
    "source": "t1"
  },
  {
    "id": "trailer1-teaser",
    "label": "Trailer 1 teaser plate",
    "videoSrc": "/videos/cinema/trailer1-teaser.mp4",
    "posterSrc": "/images/cinema/trailer1-teaser.jpg",
    "duration": 12,
    "source": "t1"
  },
  {
    "id": "trailer2-teaser",
    "label": "Trailer 2 teaser plate",
    "videoSrc": "/videos/cinema/trailer2-teaser.mp4",
    "posterSrc": "/images/cinema/trailer2-teaser.jpg",
    "duration": 12,
    "source": "t2"
  }
] as const satisfies readonly CinemaClip[];

export const cinemaById = Object.fromEntries(
  cinemaClips.map((c) => [c.id, c]),
) as Record<string, CinemaClip>;
